apiVersion: v1
kind: Pod
metadata:
 name: teja-pod
spec:
 securityContext:
  runAsUser: 1001



#container security context
apiVersion: v1
kind: Pod
metadata:
 name: teja-pod
spec:
 containers:
  - name: teja
    image: ubuntu
    command: ["sleep", "3600"]
    securityContext:
     runAsUser: 1001
     capabilities:
      add: ["MAC_ADMIN"]
