apiVersion: v1
kind: Pod
metadata:
 name: teja-secret-pod
spec:
 containers:
 - name: teja-nginx
   image: nginx
   ports:
   - containerPort: 8080
   envFrom:
    - secretRef:
       name: teja-secret
